name: covid19tracker
description: COVID-19 Tracker app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: any
  intl: any
  flash: any
  get_it: any
  provider: any
  fl_chart: any
  flutter_svg: any
  url_launcher: any
  pull_to_refresh: any
  font_awesome_flutter: any
  flutter_statusbarcolor: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf


